### ISSUE TITLE
Criação do Cenário de eCommerce passado pelo Professor

### ISSUE THREAD

**Issue by HugoPeressin** [TatiTheFreaK/UnimepGovTI01#13]

**Comment by ghost** [comment]
Feito em aula até a página 28, junto com o professor!

**Comment by HugoPeressin** [comment]
Cria um issue lá para a apresentação de hoje, vlw!

Em seg, 10 de dez de 2018 às 07:53, Gabriel Rocha <notifications@github.com>
escreveu:
